import os
from datetime import date

def generate_markdown_report(articles: list, filename: str = "market_watch_report.md"):
    """
    Generates a bilingual Markdown report from the processed articles.
    """
    today = date.today().strftime("%d %b %Y")
    
    markdown_content = f"""# 📈 Market Watch: Corporate News
**Date:** {today}
**Generated by:** AI News Agent (Multi-Agent System)

---

"""
    
    if not articles:
        markdown_content += "\n*No significant corporate news found for today.*"
    else:
        for idx, article in enumerate(articles):
            # Extract fields with safe defaults
            company_name = article.get('name', 'N/A')
            ticker = article.get('ticker', 'N/A')
            title_en = article.get('title', 'No Title')
            title_zh = article.get('title_translated', '')
            summary_en = article.get('summary', 'No summary available.')
            summary_zh = article.get('summary_translated', '')
            link = article.get('url', '#')

            # Format: Header with Company & Ticker
            markdown_content += f"## {idx + 1}. {company_name} ({ticker})\n\n"
            
            # Bilingual Headlines
            markdown_content += f"### 🇬🇧 {title_en}\n"
            markdown_content += f"### 🇨🇳 {title_zh}\n\n"
            
            # Bilingual Summaries in a quote block or clean paragraph
            markdown_content += f"**Summary:**\n{summary_en}\n\n"
            markdown_content += f"**摘要:**\n{summary_zh}\n\n"
            
            # Source Link
            markdown_content += f"🔗 [Read Source Article]({link})\n"
            markdown_content += "---\n\n"

    # Write to file
    with open(filename, "w", encoding="utf-8") as f:
        f.write(markdown_content)
    
    print(f"Report successfully written to {os.path.abspath(filename)}")